# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FIAvADVjjCroHvYsgAsfMIj9EYDRkbHD
"""



import streamlit as st


st.write("hello worrld")

